"""Added or removed column in Config

Revision ID: 31cad177e954
Revises: bd2678942208
Create Date: 2024-04-09 11:34:48.138123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31cad177e954'
down_revision: Union[str, None] = 'bd2678942208'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('g6_board', sa.Column('gr_id', sa.String(length=255), nullable=True, default='community'))
    op.create_foreign_key(None, 'g6_board', 'g6_group', ['gr_id'], ['gr_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'g6_board', type_='foreignkey')
    op.drop_column('g6_board', 'gr_id')
    # ### end Alembic commands ###
