"""Added or removed column in Config

Revision ID: 54abf2ae391f
Revises: cb213f20a29b
Create Date: 2024-04-09 11:49:20.434346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54abf2ae391f'
down_revision: Union[str, None] = 'cb213f20a29b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('g6_board', sa.Column('gr_id', sa.String(length=255), nullable=True))
    op.execute("UPDATE g6_board SET gr_id = 'community' WHERE gr_id IS NULL")
    # op.add_column('g6_board', sa.Column('gr_id', sa.String(length=255), nullable=False, default=''))
    op.create_foreign_key(None, 'g6_board', 'g6_group', ['gr_id'], ['gr_id'])
    op.alter_column('g6_board', 'gr_id', nullable=False)

    # with op.batch_alter_table('g6_board', schema=None) as batch_op:
    #     batch_op.alter_column('gr_id', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'g6_board', type_='foreignkey')
    op.drop_column('g6_board', 'gr_id')
    # ### end Alembic commands ###
