"""Added or removed column in Config

Revision ID: b43b4c4d4de7
Revises: 
Create Date: 2024-04-09 10:35:57.922700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b43b4c4d4de7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idex_wr_is_comment_qa', table_name='g6_write_qa')
    op.drop_index('idx_wr_num_reply_qa', table_name='g6_write_qa')
    op.drop_table('g6_write_qa')
    op.drop_index('idex_wr_is_comment_free', table_name='g6_write_free')
    op.drop_index('idx_wr_num_reply_free', table_name='g6_write_free')
    op.drop_table('g6_write_free')
    op.drop_index('idex_wr_is_comment_notice', table_name='g6_write_notice')
    op.drop_index('idx_wr_num_reply_notice', table_name='g6_write_notice')
    op.drop_table('g6_write_notice')
    op.drop_index('ix_g6_member_refresh_token_id', table_name='g6_member_refresh_token')
    op.drop_index('ix_g6_member_refresh_token_mb_id', table_name='g6_member_refresh_token')
    op.drop_table('g6_member_refresh_token')
    op.drop_index('idex_wr_is_comment_gallery', table_name='g6_write_gallery')
    op.drop_index('idx_wr_num_reply_gallery', table_name='g6_write_gallery')
    op.drop_table('g6_write_gallery')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('g6_write_gallery',
    sa.Column('wr_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('wr_num', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('wr_reply', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('wr_parent', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('wr_is_comment', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('wr_comment', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('wr_comment_reply', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('ca_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_option', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('wr_subject', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('wr_seo_title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_link1', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('wr_link2', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('wr_link1_hit', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('wr_link2_hit', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('wr_hit', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('wr_good', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('wr_nogood', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('mb_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('wr_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_homepage', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('wr_file', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('wr_last', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('wr_ip', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_facebook_user', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_twitter_user', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_1', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_2', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_3', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_4', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_5', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_6', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_7', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_8', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_9', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_10', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('wr_id', name='g6_write_gallery_pkey')
    )
    op.create_index('idx_wr_num_reply_gallery', 'g6_write_gallery', ['wr_num', 'wr_reply'], unique=False)
    op.create_index('idex_wr_is_comment_gallery', 'g6_write_gallery', ['wr_is_comment'], unique=False)
    op.create_table('g6_member_refresh_token',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('mb_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('refresh_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='g6_member_refresh_token_pkey'),
    sa.UniqueConstraint('refresh_token', name='g6_member_refresh_token_refresh_token_key')
    )
    op.create_index('ix_g6_member_refresh_token_mb_id', 'g6_member_refresh_token', ['mb_id'], unique=False)
    op.create_index('ix_g6_member_refresh_token_id', 'g6_member_refresh_token', ['id'], unique=False)
    op.create_table('g6_write_notice',
    sa.Column('wr_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('wr_num', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('wr_reply', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('wr_parent', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('wr_is_comment', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('wr_comment', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('wr_comment_reply', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('ca_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_option', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('wr_subject', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('wr_seo_title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_link1', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('wr_link2', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('wr_link1_hit', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('wr_link2_hit', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('wr_hit', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('wr_good', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('wr_nogood', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('mb_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('wr_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_homepage', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('wr_file', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('wr_last', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('wr_ip', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_facebook_user', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_twitter_user', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_1', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_2', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_3', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_4', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_5', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_6', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_7', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_8', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_9', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_10', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('wr_id', name='g6_write_notice_pkey')
    )
    op.create_index('idx_wr_num_reply_notice', 'g6_write_notice', ['wr_num', 'wr_reply'], unique=False)
    op.create_index('idex_wr_is_comment_notice', 'g6_write_notice', ['wr_is_comment'], unique=False)
    op.create_table('g6_write_free',
    sa.Column('wr_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('wr_num', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('wr_reply', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('wr_parent', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('wr_is_comment', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('wr_comment', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('wr_comment_reply', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('ca_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_option', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('wr_subject', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('wr_seo_title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_link1', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('wr_link2', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('wr_link1_hit', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('wr_link2_hit', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('wr_hit', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('wr_good', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('wr_nogood', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('mb_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('wr_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_homepage', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('wr_file', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('wr_last', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('wr_ip', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_facebook_user', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_twitter_user', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_1', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_2', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_3', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_4', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_5', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_6', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_7', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_8', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_9', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_10', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('wr_id', name='g6_write_free_pkey')
    )
    op.create_index('idx_wr_num_reply_free', 'g6_write_free', ['wr_num', 'wr_reply'], unique=False)
    op.create_index('idex_wr_is_comment_free', 'g6_write_free', ['wr_is_comment'], unique=False)
    op.create_table('g6_write_qa',
    sa.Column('wr_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('wr_num', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('wr_reply', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('wr_parent', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('wr_is_comment', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('wr_comment', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('wr_comment_reply', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('ca_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_option', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('wr_subject', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('wr_seo_title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_link1', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('wr_link2', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('wr_link1_hit', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('wr_link2_hit', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('wr_hit', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('wr_good', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('wr_nogood', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('mb_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('wr_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_homepage', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('wr_file', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('wr_last', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('wr_ip', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_facebook_user', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_twitter_user', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_1', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_2', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_3', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_4', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_5', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_6', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_7', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_8', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_9', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('wr_10', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('wr_id', name='g6_write_qa_pkey')
    )
    op.create_index('idx_wr_num_reply_qa', 'g6_write_qa', ['wr_num', 'wr_reply'], unique=False)
    op.create_index('idex_wr_is_comment_qa', 'g6_write_qa', ['wr_is_comment'], unique=False)
    # ### end Alembic commands ###
