"""Added or removed column in Config

Revision ID: bd2678942208
Revises: df1f5a890e80
Create Date: 2024-04-09 11:33:18.644556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd2678942208'
down_revision: Union[str, None] = 'df1f5a890e80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('g6_board_gr_id_fkey', 'g6_board', type_='foreignkey')
    op.drop_column('g6_board', 'gr_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('g6_board', sa.Column('gr_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_foreign_key('g6_board_gr_id_fkey', 'g6_board', 'g6_group', ['gr_id'], ['gr_id'])
    # ### end Alembic commands ###
