"""Added or removed column in Config

Revision ID: cb213f20a29b
Revises: 74c61bf83eea
Create Date: 2024-04-09 11:48:38.957012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb213f20a29b'
down_revision: Union[str, None] = '74c61bf83eea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('g6_board_gr_id_fkey', 'g6_board', type_='foreignkey')
    op.drop_column('g6_board', 'gr_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('g6_board', sa.Column('gr_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_foreign_key('g6_board_gr_id_fkey', 'g6_board', 'g6_group', ['gr_id'], ['gr_id'])
    # ### end Alembic commands ###
