"""Added or removed column in Config

Revision ID: df1f5a890e80
Revises: e68204833990
Create Date: 2024-04-09 11:22:02.685644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df1f5a890e80'
down_revision: Union[str, None] = 'e68204833990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('g6_poll_etc', 'test')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('g6_poll_etc', sa.Column('test', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
