"""Added or removed column in Config

Revision ID: e68204833990
Revises: b43b4c4d4de7
Create Date: 2024-04-09 11:15:07.032457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e68204833990'
down_revision: Union[str, None] = 'b43b4c4d4de7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('g6_poll_etc', sa.Column('test', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('g6_poll_etc', 'test')
    # ### end Alembic commands ###
